trigger: ["master"]
pr: ["master"]

jobs:
# Check formatting
- job: rustfmt
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: ci/azure-rustfmt.yml

# Run tests
- template: ci/azure-test-all.yml
