jobs:
- job: cargo_test_all
  displayName: cargo test
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      stable:
        rust_version: stable
  steps:

  - template: azure-install-rust.yml
    parameters:
      rust_version: $(rust_version)

  - script: cargo test
    displayName: cargo test
