name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  # This is the minimum supported Rust version of this crate.
  # When updating this, the reminder to update the minimum supported
  # Rust version in README.md and .clippy.toml.
  minrust: 1.45.2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        run: rustup update stable
      - run: rustup component add rust-src
      - run: cargo test --all-features

  minrust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update ${{ env.minrust }} && rustup default ${{ env.minrust }}
      - run: cargo build --all-features

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        run: rustup update stable
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        run: rustup update stable
      - run: cargo clippy --all-features

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update nightly && rustup default nightly
      - run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: -Dwarnings
